anguage: python

python:
  - "3.6"

cache: pip
install: 
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install codecov
  - pip install pytest-cov

script: 
  - python3 -m pytest -v --cov app/api/tests
  
after_success:
  - codecov
  - coveralls